<?php

namespace BanqueBundle\Repository;

use Doctrine\ORM\EntityRepository;
use BanqueBundle\Entity\User;

/**
 * CompteCourantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompteCourantRepository extends EntityRepository
{

    public function findbyuser(User $user){
        $qb = $this->createQueryBuilder('c');

        $qb->where('c.user = :user')
            ->setParameter('user', $user);

        return $qb->getQuery()->getSingleResult();
    }
}
