<?php

namespace BanqueBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MessageSupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageSupportRepository extends EntityRepository
{
}
