<?php

namespace BanqueBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StatSoldeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatSoldeRepository extends EntityRepository
{
}
