<?php

namespace BanqueBundle\Repository;

use Doctrine\ORM\EntityRepository;
use BanqueBundle\Entity\CompteCourant;

/**
 * TransfertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransfertRepository extends EntityRepository
{

    public function findCrediteur(CompteCourant $compte){
        $qb = $this->createQueryBuilder('t');

        $qb->where('t.crediteur = :compte')
            ->setParameter('compte', $compte)
            ->select('COUNT(t)');
        return $qb->getQuery()->getSingleScalarResult();
    }

    public function findTransferts(CompteCourant $compte){
        $qb = $this->createQueryBuilder('t');

        $qb->where('t.debiteur = :compte')
            ->orWhere('t.crediteur =:compte')
            ->setParameter('compte', $compte)
            ->orderBy('t.id','DESC')
            ->setMaxResults(20);
            
        return $qb->getQuery()->getResult();
    }
}
